---
openapi: 3.0.1
info:
  title: Tesla Test-Drive
  version: v1
paths:
  "/api/users":
    get:
      summary: List all users
      tags:
      - Users
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    username:
                      type: string
                    email:
                      type: string
                  required:
                  - id
                  - username
                  - email
servers:
- url: http://127.0.0.1:3000
  variables:
    defaultHost:
      default: http://127.0.0.1:3000
